### ISSUE TITLE
sonar:bit 

### ISSUE THREAD

**Issue by emilyLMZ** [elecfreaks/pxt-sonarbit#1]
I ve been trying to make mesures of a distance with ultrasound (I've tried sonar:bit V1.6) . The mesures the micro:bit gives me are always 0.64 times the real distance mesured with a ruler. ( I did tests from 5cm to 200 cm)
The code I ve been using is the code that is proposed by elecfreaks.:  https://makecode.microbit.org/_b7JL2Yd3q3Km
Could you tell me why do i find this proportional coefficent equal to 0,64 ?

Bests regards,

Emily

**Comment by jvsantos1979** [comment]
Hello, Do you have a solution? Thank you!

**Comment by emilyLMZ** [comment]
If you code with python, it works.

**Comment by jvsantos1979** [comment]
And how?

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jvsantos1979** [comment]
If i Buy something i would like to know how this works. :(

Can you help me, please?

Obter o Outlook para iOS<https://aka.ms/o0ukef>

________________________________
De: José Santos <mat_tic_josesantos@c-guadalupe.com>
Enviado: terça-feira, março 26, 2019 5:34 PM
Para: elecfreaks/pxt-sonarbit; elecfreaks/pxt-sonarbit
Cc: Comment
Assunto: Re: [elecfreaks/pxt-sonarbit] sonar:bit (#1)

And how?

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elecfreaks** [comment]
fix

**Comment by jvsantos1979** [comment]
For 1.4 Version doesn´t work. 
![WhatsApp Image 2019-04-01 at 09 49 15](https://user-images.githubusercontent.com/48958555/55315532-6afdee00-5464-11e9-9d35-b6c2e28089a1.jpeg)
![WhatsApp Image 2019-04-01 at 09 49 16](https://user-images.githubusercontent.com/48958555/55315539-6c2f1b00-5464-11e9-97d8-f9c375b62401.jpeg)
![Sem Título](https://user-images.githubusercontent.com/48958555/55315549-6e917500-5464-11e9-81da-68b8635380bc.png)

**Comment by elecfreaks** [comment]
@jvsantos1979 please contact your local distributor, you can find the one who sells it and they have the solutions.
